name: Build NPM Package
on:
  workflow_call:
    inputs:
      uploadBuild:
        type: boolean
        required: false
        default: false
        description: 'Upload distribution files to Github'
    outputs:
      uploadedBuildName:
        description: "If a build is uploaded, this name will be output"
        value: ${{ jobs.build.outputs.uploadedBuildName }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      uploadedBuildName: ${{ steps.finish-output.outputs.uploadedBuildName }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test:ci
    - name: Build
      run: npm run build
    - name: Package Artifacts
      if: inputs.uploadBuild
      run: |
        echo '::echo::on'
        echo "PACKAGE_FILE=$(npm pack | tail -1)" >> $GITHUB_ENV
    - name: Upload Artifacts
      if: inputs.uploadBuild
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_FILE }}
        path: ${{ env.PACKAGE_FILE }}
    - id: finish-output
      name: Output Result
      if: inputs.uploadBuild
      run: |
        echo "::set-output name=uploadedBuildName::${PACKAGE_FILE}"
