---
name: Publish NPM Package

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      imageScope:
        type: string
        required: true
        description: ""
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Read package.json
        id: read-package-json
        run: |
          JSON=$(cat ./package.json)
          echo "::set-output name=string::${JSON//'%'/'%25'}"
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          build-args: "ENVIRONMENT=production"
          file: "docker/Dockerfile"
          platform: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          context: .
          push: true
          tags: |
            ${{ inputs.imageScope }}:latest
            ${{ inputs.imageScope }}:${{fromJson(steps.read-package-json.outputs.string)}}
