---
name: Build NPM Package

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      uploadBuild:
        type: boolean
        required: false
        default: false
        description: "Upload distribution files to Github"
    outputs:
      uploadedBuildName:
        description: "If a build is uploaded, this name will be output"
        value: ${{ jobs.build.outputs.uploadedBuildName }}

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      uploadedBuildName: ${{ steps.finish-output.outputs.uploadedBuildName }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm ci
      - name: Lint Source
        run: npm run lint
      - name: Unit Test Source
        run: npm run test:ci
      - name: Build Source
        run: npm run build
      - name: Package Artifacts
        if: inputs.uploadBuild
        run: |
          echo '::echo::on'
          echo "PACKAGE_FILE=$(npm pack | tail -1)" >> $GITHUB_ENV
      - name: Upload Artifacts
        if: inputs.uploadBuild
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_FILE }}
          path: ${{ env.PACKAGE_FILE }}
      - id: finish-output
        name: Output Result
        if: inputs.uploadBuild
        run: |
          echo "::set-output name=uploadedBuildName::${PACKAGE_FILE}"
