---
name: Publish Artifacts for Tag

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      uploadToTag:
        type: string
        required: true
        description: "Upload built Bundle to Github tag"
      uploadedBuildName:
        type: string
        required: true
        description: "Name associated with actions/upload-artifact"
    secrets:
      REPO_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Output
        run: |
          echo '::echo::on'
          echo "${{ inputs.uploadedBuildName }}"
      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.uploadedBuildName }}
          path: archive
      - name: Associate with Github Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          file: archive/*
          tag: ${{ inputs.uploadToTag }}
          overwrite: true
          file_glob: true
          prerelease: true
